# Generated by Django 5.0.3 on 2024-04-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('bachelor', 'B'), ('master', 'M'), ('ph', 'PH')], default='bachelor', max_length=20),
        ),
    ]
